### ISSUE TITLE
[Request] Retrieve all tags

### ISSUE THREAD

**Issue by fighuass** [jellyfin/jellyfin-plugin-anidb#21]
Hi, I noticed that the plugin only retrieves the tags listed at the top of an AniDB page, but those are just a few ones (I assume this section is intended to be a summary?). I'd prefer it if it could also retrieve all of them lower on the page (these ones):

![Untitled](https://user-images.githubusercontent.com/28998263/151669153-882018d5-f7ac-4900-9480-9ec19ade117a.png)

Could this be added, please?

**Comment by Nalsai** [comment]
You can set `Max Genres` in the plugin settings.
The Plugin gets all tags with a weight of at least 400. 100 is equal to half a star on the website, that means it gets all tags with at least 2 stars until it has filled Max Genres. 
If you want, I could add a setting to change the minimum weight.
