### ISSUE TITLE
Missing information "undefined"

### ISSUE THREAD

**Issue by sjiawjbssj** [jellyfin/jellyfin-plugin-anidb#39]
Some shows return only "undefined" when trying to identify them. The link to the entry from AniDB gets added but other information and images are missing.

<details><summary>Logs:</summary>
<p>
[23:54:53] [INF] [64] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item fa6b9ec1-4251-3557-2d02-533b6866a756-JK Genkai Koubi Goui Sounyuu de Bachibachi Niku Anaka: {"AniDB":"17316"}
[matroska,webm @ 0x563aa4a74700] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
[matroska,webm @ 0x563aa4a74700] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
[matroska,webm @ 0x563aa4a74700] Could not find codec parameters for stream 5 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
[matroska,webm @ 0x563aa4a74700] Could not find codec parameters for stream 6 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
[matroska,webm @ 0x563aa4a74700] Could not find codec parameters for stream 7 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
[matroska,webm @ 0x563aa4a74700] Could not find codec parameters for stream 8 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
[matroska,webm @ 0x563aa4a74700] Could not find codec parameters for stream 9 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
Unsupported codec with id 0 for input stream 3
Unsupported codec with id 0 for input stream 4
Unsupported codec with id 0 for input stream 5
Unsupported codec with id 0 for input stream 6
Unsupported codec with id 0 for input stream 7
Unsupported codec with id 0 for input stream 8
Unsupported codec with id 0 for input stream 9
[23:54:54] [INF] [3] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 1 in series JK Genkai Koubi Goui Sounyuu de Bachibachi Niku Anaka
[23:54:54] [INF] [3] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season 1, Path: , Id: ae9a5af0-91c2-cc0b-8e12-9210f800531b
[23:54:54] [INF] [3] Jellyfin.Plugin.Tvdb.Providers.TvdbMissingEpisodeProvider: Creating Season Season 1 entry for JK Genkai Koubi Goui Sounyuu de Bachibachi Niku Anaka
[23:54:54] [INF] [3] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season Season Unknown entry for JK Genkai Koubi Goui Sounyuu de Bachibachi Niku Anaka
[23:54:54] [INF] [3] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season 1, Path: , Id: ae9a5af0-91c2-cc0b-8e12-9210f800531b
[23:54:54] [WRN] [3] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.178.31:8096/Items/RemoteSearch/Apply/fa6b9ec1425135572d02533b6866a756?ReplaceAllImages=true to 192.168.178.24 in 0:00:01.7740956 with Status Code 204
</p>
</details>

![Screenshot_1](https://user-images.githubusercontent.com/101941309/178124166-ef037995-1b32-4ac7-841a-64a6d670bd08.png)
![Screenshot_2](https://user-images.githubusercontent.com/101941309/178124167-a3cc2d6f-b17e-4f5e-ad00-3103ca9f0807.png)

**Comment by Nalsai** [comment]
I can't reproduce the issue with the same filename, as shown in the screenshots. 

It looks like you might have run into AniDBs very strict api rate limiting.
Have you maybe scanned a large library and started a request to AniDB, while another metadata update was already running? (I would appreciate a description of what you were doing and maybe how many shows and episodes you were getting metadata for, until you hit this issue.)

You can delete the files for the show from the jellyfin cache anidb folder, but you are probably banned from the API for 24h, so you will just get undefined again for now.

The rate limiter built into the plugin should probably be improved, to prevent running into the api limits, but I've only encountered it once, while testing during development, so I haven't gotten around to it yet.

**Comment by sjiawjbssj** [comment]
Thanks for answering. I had that problem for about a week now so I don't think it's the api rate limit. 
I have 218 shows in that library but most of them already have their metadata.
I'm not sure if it was this file but I tried adding [anidbid-NUMBER] after the folder name for new folders and thats when I first noticed this issue. Because of the problem I removed it but it didn't fix the problem.
I'll try deleting the cache and getting a new IP as soon as I can.

**Comment by Nalsai** [comment]
Before you delete the cache, look inside the folder with the anidb id of this show and maybe send the contents of one of the files, please.

**Comment by sjiawjbssj** [comment]
Deleting the cache worked. I didn't need a new IP.
The content of the series.xml is: <error code="500">banned</error> so it I really was the api rate limit and the cache just wasn't cleared.
"Clean Cache Directory" ran just an hour ago but apparently didn't clear that folder.
Sorry that I didn't think to check that before posting.
Thanks for your fast help.
