### ISSUE TITLE
[request] Map tag '18 restricted' to Parental Rating = NC-17

### ISSUE THREAD

**Issue by sjorge** [jellyfin/jellyfin-plugin-anidb#47]
It would be nice to map the `18 restricted` tag to the *Parental Rating* value of `NC-17`

Currently manually having to lock the field and set it myself, it would be nice if it was somehow automatically mapped.

**Comment by sjorge** [comment]
Newever version of HAMA `18 restricted` tag to `X` rating and the `ecchi` tag to `NC-17`. This might be better overall.

**Comment by nalsai** [comment]
From what I understand as a non-American `NC-17` is just the "new version" of `X`. 
Ecchi doesn't strictly imply any age rating so I don't see why to map it to one.

**Comment by oddstr13** [comment]
I had to look it up, but `NC-17` is essentially a synonym for `18+`.

> *From [MPAA rating system](<https://en.wikipedia.org/wiki/Motion_Picture_Association_film_rating_system>) on Wikipedia*
> NC-17 – Adults Only
>    No one 17 and under admitted. Clearly adult. Children are not admitted.
