### ISSUE TITLE
Use of folder name identifiers.

### ISSUE THREAD

**Issue by Mihara** [jellyfin/jellyfin-plugin-anidb#65]
Jellyfin documentation currently says:

> In order to help with identifying a series, Jellyfin can make use of media provider identifiers. This can be specified in your show's folder name, for example: Series Name (2018) [tmdbid-65567] or Series Name (2018) [tvdbid-65567]

1. Is there an option to do the same for an anidb id? 
2. If yes, what's the magic word? The obvious `anidbid-xxxx` and `anidb-xxxx` did not work.
3. If not, why?...

**Comment by nalsai** [comment]
`anidbid-XXXXX` should work, but currently only in the folder of the series (seasons can't be a different id)

For example, I have a folder named "Re Zero kara Hajimeru Isekai Seikatsu OVAs [anidbid-13430]".

**Comment by Mihara** [comment]
Indeed, `anidbid-XXXXX` eventually worked after some kicking. No idea why it didn't work to start with, but I might've made a mistake somewhere else...
