### ISSUE TITLE
Use AniDB ID to search for entry

### ISSUE THREAD

**Issue by SU042002** [jellyfin/jellyfin-plugin-anidb#71]
Hi, all the animes I have are structured in a folder nicely. 

As an example, all my folders are structured like this:
11 Eyes {anidb-6751}

They have the name and the AniDB ID associated with them. Is there anyway for the plugin to just search for the ID that is in the folder name to grab information?

**Comment by nalsai** [comment]
Yes, but you need to use [anidb**id**-6751]

**Comment by SU042002** [comment]
Thank you for the solution. Eventually did manage to figure it out from older sources. Just used Bulk Rename Utility to update my folders and now it works great.
